"""
Visualization module for Parchís games.
Displays game boards and replays games from log files.
"""

import json
import math
from functools import lru_cache
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.patheffects as patheffects
from matplotlib.patches import Circle

from parchis.game.board import Board
from parchis.visualization import agentinfo_io

# The real board photo used as the board's background. All coordinates in
# this module are pixel coordinates within this specific image (measured
# directly off it -- see the constants below) -- if the image is replaced,
# every constant here needs re-measuring against the new file.
BOARD_IMAGE_PATH = Path(__file__).resolve().parent.parent.parent / 'docs' / 'images' / 'foto_parchis.png'


@lru_cache(maxsize=1)
def _load_board_image():
    """Load and cache the board photo -- shared by every ParchisVisualizer
    instance instead of re-reading the PNG off disk each time one is built."""
    return plt.imread(BOARD_IMAGE_PATH)


class ParchisVisualizer:
    """Visualizes Parchís game board (a real board photo) and replays games from logs."""

    # Color definitions
    COLORS = {
        'YELLOW': '#FFD700',
        'BLUE': '#4169E1',
        'RED': '#DC143C',
        'GREEN': '#228B22'
    }

    # Pixel dimensions of docs/images/foto_parchis.png. All position math
    # below is done in this image's pixel space and only flipped to
    # matplotlib's y-up convention at the end (see _pixel_to_data).
    IMAGE_WIDTH = 631
    IMAGE_HEIGHT = 622

    # Each corner's base-circle centroid, measured directly off the photo
    # (color-blob centroid of each corner's solid-color circle). Used both
    # to draw pieces waiting in base and, via rotation, has no bearing on
    # the track/home-lane math below (those are measured independently
    # off the arm they belong to).
    BASE_POSITIONS_PIXEL = {
        'RED': (110.6, 112.3),
        'BLUE': (518.2, 112.3),
        'GREEN': (110.7, 512.9),
        'YELLOW': (518.3, 512.9),
    }
    # Radius of a corner's base circle in the photo, used to size and
    # spread the 4 waiting-piece slots inside it.
    BASE_CIRCLE_RADIUS_PIXEL = 102.0

    # Where the board's 4 arms meet, measured as the centroid of the 4
    # base-circle centers (631x622 isn't perfectly square, so this isn't
    # exactly the image's midpoint) -- the pivot every rotated arm
    # template below is measured and rotated around.
    HUB_PIXEL = (314.5, 312.5)

    # One main-track cell's pixel spacing along an arm's length (measured
    # from 8 consecutive numbered squares' printed-digit centroids in the
    # reference photo's east/BLUE arm), and that same arm's flank-row
    # offsets from its own home-lane row (its perpendicular width). Cells
    # aren't square in this rendering -- the along-arm spacing (~29px) and
    # the cross-arm row spacing (~45px) are measured independently.
    ARM_CELL_PITCH = 29.1
    ARM_CELL_PITCH_OFFSET = 86.1  # distance from the hub to the first (hub-most) track cell
    ARM_ROW_OFFSET_FAR = 45.0     # flank row on the "far" side of the home lane (rotation-relative)
    ARM_ROW_OFFSET_NEAR = 44.5    # flank row on the "near" side of the home lane

    # Which color owns each arm -- that color's start square, its
    # HOME_ENTRY_POINTS square, and its private home lane are all in this
    # one arm (confirmed by reading the position numbers printed in
    # docs/images/foto_parchis.png). BLUE's east arm was measured directly;
    # the other 3 arms are generated by rotating BLUE's arm 90 degrees
    # counter-clockwise per step, matching the board's real N/W/S/E
    # layout (RED=north, GREEN=west, YELLOW=south).
    ARM_COLOR_BY_ROTATION_STEP = ['BLUE', 'RED', 'GREEN', 'YELLOW']

    def __init__(self):
        """Initialize the visualizer."""
        self.fig = None
        self.ax = None
        self.piece_artists = {}  # Store piece circle objects for animation
        self.highlight_artist = None  # Track the current move-highlight arrow
        self.status_artist = None  # Track the current turn/roll status text

        # Agent-value side panel (see create_board(show_value_panel=...)):
        # None/None whenever the panel wasn't requested, so draw_value_panel
        # can no-op cheaply rather than every caller having to check a
        # separate flag.
        self.value_ax_root = None
        self.value_ax_moves = None

        # Main-track coordinates (1-68), shared by all colors, and each
        # color's private home-lane coordinates (69-76), kept separate
        # since all 4 colors physically occupy a different lane despite
        # sharing the same logical position numbers (see docs/CODE_REVIEW.md).
        self.position_coords, self.home_coords = self._calculate_position_coords()

        # Corner base-circle centers, in the same data-space coordinates
        # as everything else.
        self.base_positions = {
            color: self._pixel_to_data(*px)
            for color, px in self.BASE_POSITIONS_PIXEL.items()
        }

    def _pixel_to_data(self, px, py):
        """Convert a photo pixel coordinate to matplotlib data coordinates.
        x is unchanged; y is flipped since image rows run top-to-bottom
        while matplotlib data space (and the imshow extent used to render
        the photo) runs bottom-to-top."""
        return (px, self.IMAGE_HEIGHT - py)

    @staticmethod
    def _rotate90(dx, dy, steps):
        """Rotate an (dx, dy) offset 90 degrees counter-clockwise, `steps` times."""
        for _ in range(steps):
            dx, dy = -dy, dx
        return dx, dy

    @classmethod
    def _arm_cell_offset(cls, k):
        """Data-space distance from the hub to the k-th track cell (k=1..8,
        1=hub-most, 8=edge-most) along an arm's length, in the reference
        (BLUE, east-pointing) orientation."""
        return cls.ARM_CELL_PITCH_OFFSET + (k - 1) * cls.ARM_CELL_PITCH

    @classmethod
    def _build_track_template(cls):
        """
        Build one arm's 17-cell main-track walk, as (dx, dy) offsets from
        the hub, in BLUE's east-pointing arm -- the one directly measured
        off docs/images/foto_parchis.png. Every arm in the photo is a
        straight 3-row x 8-column rectangle (2 flank rows of 8 main-track
        cells + 1 middle home-lane row), not a curve: the walk runs along
        the "near" flank row from the hub out to the edge (8 cells), turns
        at the edge onto the home-lane row (1 cell -- this is that color's
        HOME_ENTRY_POINTS square), then returns along the "far" flank row
        from the edge back to the hub (8 cells). 8+1+8 = 17.

        Returns:
            list[tuple[float, float]]: 17 offsets, index 0 = the cell
            adjacent to the hub on the near flank, index 8 = the turn
            cell (edge, home-lane row), index 16 = the cell adjacent to
            the hub on the far flank.
        """
        template = []
        for k in range(1, 9):
            template.append((cls._arm_cell_offset(k), -cls.ARM_ROW_OFFSET_NEAR))
        template.append((cls._arm_cell_offset(8), 0.0))
        for k in range(8, 0, -1):
            template.append((cls._arm_cell_offset(k), cls.ARM_ROW_OFFSET_FAR))
        return template

    @classmethod
    def _build_home_template(cls):
        """
        Build one color's 7-cell private home-lane walk (positions 69-75),
        as (dx, dy) offsets from the hub, same orientation as
        _build_track_template -- straight along the home-lane row, from
        the cell adjacent to this color's own turn cell (edge-most on this
        row -- see _build_track_template's index 8) inward to the one just
        short of the hub. A piece enters home immediately after its turn
        cell, so 69 must be the edge-most home-lane cell, not the hub-most
        one, and travel inward from there. Position 76 (the finish) isn't
        part of this walk -- every color's pieces finish at the hub itself.
        """
        return [(cls._arm_cell_offset(k), 0.0) for k in range(7, 0, -1)]

    def _calculate_position_coords(self):
        """
        Compute (x, y) data-space coordinates for the main track (1-68)
        and, per color, for that color's private home lane (69-76).

        One arm's walk is measured once, directly off the reference photo
        (_build_track_template / _build_home_template), and rotated 90
        degrees per arm to produce all four -- see
        ARM_COLOR_BY_ROTATION_STEP for which color owns which arm and why
        BLUE is the unrotated reference.

        Returns:
            tuple: (position_coords, home_coords)
                position_coords: dict {1..68: (x, y)}
                home_coords: dict {color: {69..76: (x, y)}}
        """
        track_template = self._build_track_template()
        home_template = self._build_home_template()
        hub = self._pixel_to_data(*self.HUB_PIXEL)

        position_coords = {}
        home_coords = {color: {} for color in self.COLORS}

        for step, color in enumerate(self.ARM_COLOR_BY_ROTATION_STEP):
            # The arm's first main-track cell (index 0, hub-most on the
            # near flank) sits 13 cells before this color's own start
            # square -- i.e. this color's start is the 14th cell of its
            # own arm, not the first. Verified against Board.STARTING_POSITIONS
            # for all 4 colors against the photo's printed numbers.
            arm_start_pos = (Board.STARTING_POSITIONS[color] - 14) % Board.MAIN_TRACK_SIZE + 1

            for i, (dx, dy) in enumerate(track_template):
                rx, ry = self._rotate90(dx, dy, step)
                pos = (arm_start_pos + i - 1) % Board.MAIN_TRACK_SIZE + 1
                position_coords[pos] = (hub[0] + rx, hub[1] + ry)

            for i, (dx, dy) in enumerate(home_template):
                rx, ry = self._rotate90(dx, dy, step)
                home_coords[color][Board.HOME_COLUMN_START + i] = (hub[0] + rx, hub[1] + ry)

            # All 4 colors finish at the same physical point: the hub.
            home_coords[color][Board.FINAL_POSITION] = hub

        return position_coords, home_coords

    # Height (in the same pixel units as everything else) of the blank
    # strip left below the photo for the turn/roll status line -- kept
    # outside the imshow extent so it never overlaps board art.
    STATUS_STRIP_HEIGHT = 55

    def create_board(self, show_value_panel=False):
        """Create and return a figure with the Parchís board, using the
        real board photo as the background.

        show_value_panel=False (the default) is byte-for-byte the same
        figure/axes layout as before this option existed -- no behavior
        change for any existing caller. When True, the board shares the
        figure with a second panel (see draw_value_panel) showing an
        instrumented agent's decision-time value data: value_ax_root (the
        current position's win-probability per seat) and value_ax_moves
        (one bar per candidate move at the decision being replayed).
        """
        if show_value_panel:
            self.fig = plt.figure(figsize=(18, 12.5))
            gs = self.fig.add_gridspec(2, 2, width_ratios=[3, 2], height_ratios=[1, 2])
            self.ax = self.fig.add_subplot(gs[:, 0])
            self.value_ax_root = self.fig.add_subplot(gs[0, 1])
            self.value_ax_moves = self.fig.add_subplot(gs[1, 1])
            self.value_ax_root.axis('off')
            self.value_ax_moves.axis('off')
        else:
            self.fig, self.ax = plt.subplots(figsize=(12, 12.5))
            self.value_ax_root = None
            self.value_ax_moves = None

        self.ax.set_xlim(0, self.IMAGE_WIDTH)
        self.ax.set_ylim(-self.STATUS_STRIP_HEIGHT, self.IMAGE_HEIGHT)
        self.ax.set_aspect('equal')
        self.ax.axis('off')

        self.ax.imshow(
            _load_board_image(),
            extent=(0, self.IMAGE_WIDTH, 0, self.IMAGE_HEIGHT),
            zorder=0,
        )

        return self.fig, self.ax

    def set_status(self, text, color='black'):
        """Show a line of status text (turn number, whose roll, the roll
        result) in the strip below the board -- kept as a distinct method
        from the piece/highlight drawing so replay_game_from_log can update
        it independently of whether a given roll produced a move."""
        if self.status_artist is not None:
            self.status_artist.remove()
            self.status_artist = None

        self.status_artist = self.ax.text(
            self.IMAGE_WIDTH / 2, -self.STATUS_STRIP_HEIGHT / 2, text,
            fontsize=15, fontweight='bold', ha='center', va='center', color=color,
        )

    def draw_pieces(self, game_state):
        """
        Draw all pieces on the board based on game state.

        Args:
            game_state: Dict with player colors as keys, values are lists of
                       piece positions (None for in base, 1-76 for on board)
        """
        # Clear existing pieces (each entry is (circle, number_label) --
        # see _draw_piece_in_base/_draw_piece_on_board).
        for circle, label in self.piece_artists.values():
            circle.remove()
            label.remove()
        self.piece_artists.clear()

        # A square can hold up to Board.MAX_PIECES_PER_SQUARE (2) pieces at
        # once (own or opponent's, on a safe square). Count how many
        # pieces land on each square before drawing, so a lone piece can
        # be centered while two sharing a square get distinct offset
        # slots instead of both landing on the same spot (or wherever
        # their own piece_idx happens to offset them to).
        occupancy = {}
        for piece_positions in game_state.values():
            for position in piece_positions:
                if position is not None:
                    occupancy[position] = occupancy.get(position, 0) + 1
        # Home-lane positions are color-private -- two different colors'
        # pieces can't actually share one, so key those by (color, position)
        # instead of the bare (shared, main-track) position number.
        home_occupancy = {}
        for color, piece_positions in game_state.items():
            for position in piece_positions:
                if position is not None and position >= Board.HOME_COLUMN_START:
                    key = (color, position)
                    home_occupancy[key] = home_occupancy.get(key, 0) + 1

        slot_index = {}
        for color, piece_positions in game_state.items():
            for piece_idx, position in enumerate(piece_positions):
                if position is None:
                    self._draw_piece_in_base(color, piece_idx)
                    continue

                is_home = position >= Board.HOME_COLUMN_START
                key = (color, position) if is_home else position
                total_at_square = home_occupancy[key] if is_home else occupancy[key]
                slot = slot_index.get(key, 0)
                slot_index[key] = slot + 1

                self._draw_piece_on_board(color, piece_idx, position, slot, total_at_square)

    # Waiting-in-base piece layout: a fixed 2x2 grid of up to 4 same-color
    # pieces, scaled to the photo's actual base-circle radius.
    BASE_PIECE_OFFSET = 28.0
    BASE_PIECE_RADIUS = 17.0

    # Font size for the piece-index label (0-3) drawn inside every piece
    # circle -- one fixed size for base pieces (always full BASE_PIECE_RADIUS),
    # and PIECE_LABEL_FONTSIZE/PIECE_LABEL_FONTSIZE_SHARED for on-board
    # pieces (see _draw_piece_on_board -- shared squares draw smaller
    # circles, so their label needs to shrink to match).
    PIECE_LABEL_FONTSIZE = 8
    PIECE_LABEL_FONTSIZE_SHARED = 6

    def _draw_piece_label(self, x, y, piece_idx, fontsize):
        """The small 0-3 index drawn inside a piece's circle so identical-
        color pieces can be told apart and followed across a replay. White
        with a black outline stroke -- rather than a single fixed color --
        so it stays legible against all 4 piece colors (including light
        ones like YELLOW's gold) without needing a per-color text color."""
        return self.ax.text(
            x, y, str(piece_idx), ha='center', va='center',
            fontsize=fontsize, fontweight='bold', color='white', zorder=11,
            path_effects=[patheffects.withStroke(linewidth=2, foreground='black')],
        )

    def _draw_piece_in_base(self, color, piece_idx):
        """Draw a piece in its home base."""
        base_x, base_y = self.base_positions[color]

        offsets = [(-1, 1), (1, 1), (-1, -1), (1, -1)]
        ox, oy = offsets[piece_idx]
        dx, dy = ox * self.BASE_PIECE_OFFSET, oy * self.BASE_PIECE_OFFSET
        x, y = base_x + dx, base_y + dy

        piece = Circle((x, y), self.BASE_PIECE_RADIUS,
                      facecolor=self.COLORS[color],
                      edgecolor='black', linewidth=2, zorder=10)
        self.ax.add_patch(piece)
        label = self._draw_piece_label(x, y, piece_idx, self.PIECE_LABEL_FONTSIZE)

        piece_id = f"{color}_{piece_idx}"
        self.piece_artists[piece_id] = (piece, label)

    def _lookup_coords(self, color, position):
        """
        Resolve a piece's (x, y) given its color and logical position
        (1-68 main track, 69-76 home column). Home-column positions are
        color-specific -- all 4 colors reuse the same logical numbers for
        physically different lanes -- so `color` determines which lane is
        consulted; main-track positions are shared and color-independent.

        Returns:
            tuple[float, float] or None: coordinates, or None if the
            position isn't found (e.g. an unrecognized color/position).
        """
        if position >= Board.HOME_COLUMN_START:
            return self.home_coords.get(color, {}).get(position)
        return self.position_coords.get(position)

    # On-board piece sizing: a lone piece on a square is drawn centered
    # and full-size; two pieces sharing a square are drawn smaller and
    # spread diagonally so both stay visible inside the square instead of
    # fully overlapping. Confirmed to fit (no spillover into neighboring
    # squares) via a debug render of every square's pair at these values --
    # TODO: revisit sizing/margins later for more visual breathing room.
    PIECE_RADIUS = 9.0
    SHARED_PIECE_RADIUS = 6.0
    SHARED_PIECE_OFFSET = 6.0

    def _draw_piece_on_board(self, color, piece_idx, position, slot, total_at_square):
        """Draw a piece at a specific board position.

        Args:
            slot: 0 or 1 -- this piece's draw order among the pieces
                sharing `position` this frame (see draw_pieces).
            total_at_square: how many pieces (any color) are on this
                square this frame -- 1 means draw centered, 2 means draw
                both pieces smaller and offset so they're both visible.
        """
        coords = self._lookup_coords(color, position)
        if coords is None:
            return
        x, y = coords

        if total_at_square <= 1:
            radius = self.PIECE_RADIUS
            label_fontsize = self.PIECE_LABEL_FONTSIZE
            dx, dy = 0.0, 0.0
        else:
            radius = self.SHARED_PIECE_RADIUS
            label_fontsize = self.PIECE_LABEL_FONTSIZE_SHARED
            sign = -1 if slot == 0 else 1
            dx = dy = sign * self.SHARED_PIECE_OFFSET

        px, py = x + dx, y + dy
        piece = Circle((px, py), radius,
                      facecolor=self.COLORS[color],
                      edgecolor='black', linewidth=2, zorder=10)
        self.ax.add_patch(piece)
        label = self._draw_piece_label(px, py, piece_idx, label_fontsize)

        piece_id = f"{color}_{piece_idx}"
        self.piece_artists[piece_id] = (piece, label)

    def highlight_move(self, color, piece_idx, old_pos, new_pos):
        """
        Highlight a move by showing the path from old to new position.

        Args:
            color: Player color
            piece_idx: Piece index (0-3)
            old_pos: Old position (None for base, 1-76 for board)
            new_pos: New position (1-76)
        """
        # Clear the previous move's highlight before drawing the new one --
        # since replay_game_from_log no longer recreates the whole board
        # every move (see below), a leftover arrow would otherwise persist.
        if self.highlight_artist is not None:
            self.highlight_artist.remove()
            self.highlight_artist = None

        if old_pos is None:
            return
        old_coords = self._lookup_coords(color, old_pos)
        new_coords = self._lookup_coords(color, new_pos)

        if old_coords is not None and new_coords is not None:
            # Draw arrow showing movement
            arrow = patches.FancyArrowPatch(old_coords, new_coords,
                                           arrowstyle='->', mutation_scale=20,
                                           linewidth=2, color=self.COLORS[color],
                                           alpha=0.7, zorder=5)
            self.ax.add_patch(arrow)
            self.highlight_artist = arrow

    NO_DATA_TEXT = "No agent value data\nfor this decision"

    def _draw_no_data_placeholder(self, ax, text=None):
        ax.clear()
        ax.axis('off')
        ax.text(0.5, 0.5, text or self.NO_DATA_TEXT, ha='center', va='center',
                 fontsize=11, color='gray', transform=ax.transAxes, wrap=True)

    def clear_value_panel(self):
        """Blank both value-panel axes (a no-op if show_value_panel was
        False, i.e. the axes are None)."""
        if self.value_ax_root is None:
            return
        self._draw_no_data_placeholder(self.value_ax_root)
        self._draw_no_data_placeholder(self.value_ax_moves)

    def draw_value_panel(self, decision, player_colors_by_seat):
        """Render one decision's agent-value data into the two side-panel
        axes created by create_board(show_value_panel=True) -- a no-op if
        that panel wasn't requested (axes are None). `decision` is one
        entry from agentinfo_io.decision_for_roll (or None, meaning no
        agent data exists for the roll currently being replayed: no
        sidecar at all, an uninstrumented seat, or a roll with no real
        decision -- see agentinfo_io's module docstring). `decision['kind']`
        is "search" (root_value/move_values, per-seat win-probability
        vectors) or "heuristic" (move_scores, a raw per-move scalar that is
        NOT a probability -- labeled differently so it isn't mistaken for
        one).

        player_colors_by_seat: {seat: color_str}, built once from the log's
        metadata, used to color/label the root-value bars.
        """
        if self.value_ax_root is None:
            return  # show_value_panel was False for this replay

        if decision is None:
            self.clear_value_panel()
            return

        self._draw_root_value_bars(decision, player_colors_by_seat)
        self._draw_move_value_bars(decision)

    def _draw_root_value_bars(self, decision, player_colors_by_seat):
        ax = self.value_ax_root
        root_value = decision.get('root_value')
        if root_value is None:
            # A heuristic decision has no position-level value estimate --
            # only per-move scores (see _draw_move_value_bars).
            self._draw_no_data_placeholder(ax, "No position-value estimate\n(heuristic agent)")
            return

        ax.clear()
        seats = list(range(len(root_value)))
        colors = [self.COLORS.get(player_colors_by_seat.get(s), '#888888') for s in seats]
        labels = [f"P{s} {player_colors_by_seat.get(s, '?')}" for s in seats]
        y_pos = np.arange(len(seats))

        ax.barh(y_pos, root_value, color=colors, edgecolor='black')
        ax.set_yticks(y_pos)
        ax.set_yticklabels(labels, fontsize=9)
        ax.set_xlim(0, 1)
        ax.set_title('Position value (win probability)', fontsize=10)
        for i, v in enumerate(root_value):
            ax.text(min(v + 0.02, 0.92), i, f"{v:.2f}", va='center', fontsize=8)

    def _draw_move_value_bars(self, decision):
        ax = self.value_ax_moves
        chosen_piece_id = decision.get('chosen_piece_id')

        if decision['kind'] == 'search' and decision.get('move_values'):
            seat = decision['seat']
            items = sorted(decision['move_values'].items(), key=lambda kv: int(kv[0]))
            piece_ids = [int(pid) for pid, _v in items]
            values = [v[seat] for _pid, v in items]
            title = "Candidate moves: win probability if chosen"
            xlim = (0, 1)
        elif decision['kind'] == 'heuristic' and decision.get('move_scores'):
            items = sorted(decision['move_scores'].items(), key=lambda kv: int(kv[0]))
            piece_ids = [int(pid) for pid, _v in items]
            values = [v for _pid, v in items]
            title = "Candidate moves: heuristic score (not a probability)"
            xlim = None
        else:
            self._draw_no_data_placeholder(ax)
            return

        ax.clear()
        y_pos = np.arange(len(piece_ids))
        bar_colors = ['#333333' if pid == chosen_piece_id else '#bbbbbb' for pid in piece_ids]
        bars = ax.barh(y_pos, values, color=bar_colors)
        for bar, pid in zip(bars, piece_ids):
            if pid == chosen_piece_id:
                bar.set_edgecolor('red')
                bar.set_linewidth(2.5)

        ax.set_yticks(y_pos)
        ax.set_yticklabels([
            f"piece {pid}" + ("  ← chosen" if pid == chosen_piece_id else "")
            for pid in piece_ids
        ], fontsize=9)
        if xlim is not None:
            ax.set_xlim(*xlim)
        ax.set_title(title, fontsize=10)
        for i, v in enumerate(values):
            ax.text(v, i, f" {v:.2f}", va='center', fontsize=8)

    def show(self):
        """Display the board."""
        plt.tight_layout()
        plt.show()

    def save(self, filepath):
        """Save the board to a file."""
        plt.tight_layout()
        plt.savefig(filepath, dpi=150, bbox_inches='tight')
        print(f"Board saved to {filepath}")


def replay_game_from_log(log_filepath, step_by_step=True, save_frames=False,
                          agentinfo_filepath=None, show_value_panel=None):
    """
    Replay a game from a log file with visualization.

    Args:
        log_filepath: Path to the game log JSON file
        step_by_step: If True, wait for user input between turns
        save_frames: If True, save each frame as an image
        agentinfo_filepath: Path to a sidecar agent-value JSON (see
            parchis.visualization.agentinfo_io), or None to auto-detect one
            next to log_filepath via agentinfo_io.agentinfo_path_for.
        show_value_panel: Whether to render the agent-value side panel.
            None (default) auto-enables it iff an agentinfo sidecar was
            found/loaded, so old calls/logs are visually unaffected; pass
            True/False to force it on/off (e.g. True to show the "no data"
            placeholder for an all-random game, or False to suppress the
            panel even for an instrumented log).
    """
    # Load game log
    with open(log_filepath, 'r') as f:
        log_data = json.load(f)

    print("=" * 60)
    print("PARCHÍS GAME REPLAY")
    print("=" * 60)
    print(f"Players: {len(log_data['metadata']['players'])}")
    print(f"Total turns: {log_data['result']['total_turns']}")
    print(f"Winner: {log_data['result']['winner_color']}")
    print("=" * 60)

    if agentinfo_filepath is not None:
        with open(agentinfo_filepath) as f:
            agentinfo_data = json.load(f)
    else:
        agentinfo_data = agentinfo_io.load_agentinfo(log_filepath)

    if show_value_panel is None:
        show_value_panel = agentinfo_data is not None

    # seat (arena/turn-order position, what agent_specs/DecisionRecord use)
    # and player_id (GameLogger's own, pre-rotation color-slot identity) are
    # DIFFERENT numberings -- see agentinfo_io's module docstring. Derive
    # the real mapping from the log's own turn order once, up front, rather
    # than ever comparing the two directly.
    seat_by_player_id = agentinfo_io.build_seat_by_player_id(log_data['turns'])
    player_colors_by_seat = {
        seat_by_player_id[p['id']]: p['color']
        for p in log_data['metadata']['players'] if p['id'] in seat_by_player_id
    }

    # Initialize visualizer
    viz = ParchisVisualizer()
    viz.create_board(show_value_panel=show_value_panel)

    # Initialize game state (all pieces in base)
    game_state = {}
    for player_info in log_data['metadata']['players']:
        color = player_info['color']
        game_state[color] = [None, None, None, None]  # 4 pieces, all in base

    # Draw initial state
    viz.draw_pieces(game_state)
    viz.clear_value_panel()
    plt.pause(0.1)

    if step_by_step:
        input("\nPress ENTER to start replay...")

    # Replay each turn. The step_by_step pause sits BETWEEN showing a roll
    # (+ its value panel, when available) and applying the move it led to --
    # not at the end of the turn -- so a reader sees the dice result and the
    # candidate-move probabilities first, and has time to read them, before
    # finding out what was actually played.
    quit_requested = False
    for turn_idx, turn_data in enumerate(log_data['turns']):
        if quit_requested:
            break
        turn_number = turn_data['turn_number']
        player_color = turn_data['player_color']

        print(f"\n--- Turn {turn_number}: {player_color} ---")

        # Process each roll in the turn
        for roll_idx, roll_data in enumerate(turn_data['rolls']):
            # Build the roll description shown both in the console and, via
            # set_status, directly on the board -- a roll is either a plain
            # dice roll or a bonus roll (finishing a piece grants extra
            # squares for the same turn), never both.
            if 'dice_roll' in roll_data:
                roll_desc = f"rolled {roll_data['dice_roll']}"
                print(f"  Rolled: {roll_data['dice_roll']}")
            elif 'bonus_type' in roll_data:
                roll_desc = f"{roll_data['bonus_type'].replace('_', ' ')} bonus (+{roll_data['bonus_squares']})"
                print(f"  Bonus: {roll_data['bonus_type']} ({roll_data['bonus_squares']} squares)")
            else:
                roll_desc = ""

            viz.set_status(
                f"Turn {turn_number} — {player_color}: {roll_desc}",
                color=viz.COLORS[player_color],
            )

            # Show this decision's value data (if any) at the SAME beat as
            # the roll -- before the move below is applied -- so the pause
            # right after this is a genuine "roll's in, move's not yet
            # played" moment: the reader can see the dice result and the
            # candidate-move probabilities before the outcome is revealed.
            decision = agentinfo_io.decision_for_roll(turn_data, roll_idx, agentinfo_data, seat_by_player_id)
            viz.draw_value_panel(decision, player_colors_by_seat)

            plt.pause(0.1)  # flush the roll+panel render before blocking on input
            if step_by_step:
                user_input = input("Press ENTER to see the move (or 'q' to quit): ")
                if user_input.lower() == 'q':
                    quit_requested = True
                    break

            if roll_data['move']:
                move = roll_data['move']
                piece_id = move['piece_id']
                old_pos = move['old_position']
                new_pos = move['new_position']
                move_type = move['move_type']

                print(f"    Piece {piece_id}: {old_pos} → {new_pos} ({move_type})")

                # Update game state
                game_state[player_color][piece_id] = new_pos

                # Handle captures
                for captured in move['captured']:
                    cap_color = captured['color']
                    cap_id = captured['piece_id']
                    game_state[cap_color][cap_id] = None
                    print(f"    Captured {cap_color} piece {cap_id}!")

                # Redraw pieces on the existing board -- create_board() used
                # to be called here on every move, allocating a brand-new
                # matplotlib Figure/Axes each time and never closing the old
                # one (a ~150-turn replay would open ~300 windows). Both
                # draw_pieces() and highlight_move() already clear their own
                # previous artists before drawing, so reusing self.ax is
                # sufficient.
                viz.draw_pieces(game_state)
                viz.highlight_move(player_color, piece_id, old_pos, new_pos)
            else:
                # A roll with no move (e.g. every piece is blocked or still
                # in base on a non-1/6 roll) still happened and should still
                # be visible on its own beat, not skipped silently -- clear
                # any stale highlight from a previous roll so it doesn't
                # look like this roll caused that earlier move.
                if viz.highlight_artist is not None:
                    viz.highlight_artist.remove()
                    viz.highlight_artist = None

            if save_frames:
                frame_path = f"replay_frame_{turn_number:04d}_{roll_idx:02d}.png"
                viz.save(frame_path)

            # Flush the just-applied move immediately (rather than relying
            # on the next roll's own pre-input pause to do it) so it's
            # visible even when this was the very last roll of the replay.
            # In --auto mode this doubles as the original pacing delay.
            plt.pause(0.1 if step_by_step else 0.5)

    print("\n" + "=" * 60)
    print("REPLAY COMPLETE")
    print("=" * 60)

    viz.show()


if __name__ == "__main__":
    # This module is a library used by visualize_game.py (full-featured CLI)
    # and demo_visualization.py (play-then-replay demo); running it directly
    # only supports the bare "replay this log file" case for quick manual
    # checks.
    import sys

    if len(sys.argv) > 1:
        log_file = sys.argv[1]
        step_by_step = '--auto' not in sys.argv
        save_frames = '--save-frames' in sys.argv
        replay_game_from_log(log_file, step_by_step, save_frames)
    else:
        print("Usage: python -m parchis.visualization.visualizer <log_file> [--auto] [--save-frames]")
        print("For a full-featured CLI, use: python -m parchis.visualization.visualize_game --latest")
        print("For an end-to-end demo (play + visualize), use: python -m parchis.visualization.demo_visualization")
